"""Add wallet_address and login_nonce

Revision ID: 284eba578347
Revises: 0077712aa980
Create Date: 2025-05-05 17:56:20.365842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284eba578347'
down_revision = '0077712aa980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['chain_address'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=42), nullable=True))
        batch_op.add_column(sa.Column('login_nonce', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(None, ['wallet_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('login_nonce')
        batch_op.drop_column('wallet_address')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
